# Generated by Django 4.1.1 on 2023-02-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_usersettings_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='send_push',
            new_name='is_send_push',
        ),
    ]
